-- Coretax (DJP) support: faktur keluaran XML export metadata, NSFP and
-- bukti potong / retur records. Metadata and presentation only — no ledger
-- or amount change.
--
-- Part 1 (generated by `prisma migrate diff`): new enums and columns.
-- Part 2 (hand-authored): NPWP normalization of existing rows, format CHECKs,
-- the live-NSFP unique index, and the PPN-OUT-11 Coretax presentation flag.
--
-- NPWP: the API now stores an NPWP as its 16 digits only (the Coretax TIN).
-- A legacy 15-digit NPWP (e.g. '01.234.567.8-901.000') becomes '0' + its 15
-- digits — DJP's 16-digit form of a legacy NPWP (PMK 112/2022; a resident
-- individual uses the NIK instead, which an operator must enter by hand).
-- Existing rows, in ONE DO block (all-or-nothing):
--   1. BLOCKING — a LIVE row whose npwp, stripped of '.', '-' and white space,
--      is neither blank nor 15/16 digits fails the deploy (nothing changed);
--      the message lists table + id + value. Fix them (UPDATE <table> SET npwp
--      = '<16 digits>' or NULL WHERE id = '<id>'), then
--      `prisma migrate resolve --rolled-back 20261010000000_coretax` and re-run
--      `prisma migrate deploy`.
--   2. AUTO-FIX — every other non-conforming value is rewritten (stripped;
--      15 digits → '0' + 15; blank → NULL; a soft-deleted partner's unfixable
--      value → NULL). Each change is an audit_log row (method 'MIGRATION',
--      path = this migration's name, body {table, id, old, new}; list them
--      with GET /v1/audit?method=MIGRATION).
--   3. The format CHECKs added below then hold for every row.

-- ---------------------------------------------------------------------------
-- Part 1 (generated).

-- CreateEnum
CREATE TYPE "CoretaxItemType" AS ENUM ('A', 'B');

-- CreateEnum
CREATE TYPE "CoretaxBuyerDocument" AS ENUM ('TIN', 'NATIONAL_ID', 'PASSPORT', 'OTHER');

-- CreateEnum
CREATE TYPE "TaxInvoiceStatus" AS ENUM ('NONE', 'EXPORTED', 'APPROVED', 'CANCELLED');

-- AlterTable
ALTER TABLE "business_partners" ADD COLUMN     "buyer_document_number" TEXT,
ADD COLUMN     "buyer_document_type" "CoretaxBuyerDocument" NOT NULL DEFAULT 'TIN',
ADD COLUMN     "country" TEXT NOT NULL DEFAULT 'IDN',
ADD COLUMN     "nitku_suffix" TEXT NOT NULL DEFAULT '000000';

-- AlterTable
ALTER TABLE "company_settings" ADD COLUMN     "coretax_default_item_code" TEXT NOT NULL DEFAULT '000000',
ADD COLUMN     "coretax_default_item_type" "CoretaxItemType",
ADD COLUMN     "coretax_default_unit_code" TEXT,
ADD COLUMN     "nitku_suffix" TEXT NOT NULL DEFAULT '000000';

-- AlterTable
ALTER TABLE "purchase_bills" ADD COLUMN     "withholding_slip_date" DATE,
ADD COLUMN     "withholding_slip_number" TEXT;

-- AlterTable
ALTER TABLE "purchase_debit_notes" ADD COLUMN     "retur_date" DATE,
ADD COLUMN     "retur_number" TEXT;

-- AlterTable
ALTER TABLE "sales_credit_notes" ADD COLUMN     "retur_date" DATE,
ADD COLUMN     "retur_number" TEXT;

-- AlterTable
ALTER TABLE "sales_invoice_lines" ADD COLUMN     "coretax_item_code" TEXT,
ADD COLUMN     "coretax_item_type" "CoretaxItemType",
ADD COLUMN     "coretax_unit_code" TEXT;

-- AlterTable
ALTER TABLE "sales_invoices" ADD COLUMN     "coretax_exported_at" TIMESTAMP(3),
ADD COLUMN     "tax_invoice_date" DATE,
ADD COLUMN     "tax_invoice_number" TEXT,
ADD COLUMN     "tax_invoice_status" "TaxInvoiceStatus" NOT NULL DEFAULT 'NONE',
ADD COLUMN     "trx_code" TEXT,
ADD COLUMN     "withholding_slip_date" DATE,
ADD COLUMN     "withholding_slip_number" TEXT;

-- AlterTable
ALTER TABLE "tax_codes" ADD COLUMN     "coretax_vat_rate" DECIMAL(5,2),
ADD COLUMN     "dpp_nilai_lain" BOOLEAN NOT NULL DEFAULT false;

-- ---------------------------------------------------------------------------
-- Part 2 (hand-authored).

DO $$
DECLARE
  t text;
  r record;
  problems text := '';
BEGIN
  -- 1. BLOCKING: live rows whose NPWP cannot be normalized.
  FOREACH t IN ARRAY ARRAY['company_settings', 'business_partners'] LOOP
    FOR r IN EXECUTE format($q$
      SELECT id, npwp FROM %I
      WHERE npwp IS NOT NULL
        AND regexp_replace(npwp, '[.\-\s]', '', 'g') !~ '^([0-9]{15,16})?$'
        AND %s
      ORDER BY id$q$, t,
      CASE WHEN t = 'business_partners' THEN 'deleted_at IS NULL' ELSE 'true' END)
    LOOP
      problems := problems || format(E'\n  %s id %s: npwp %L is not a 15/16-digit NPWP', t, r.id, r.npwp);
    END LOOP;
  END LOOP;
  IF problems <> '' THEN
    RAISE EXCEPTION 'coretax NPWP normalization aborted:%', problems
      USING HINT = 'Set each listed npwp to its 16 digits (or NULL), then mark this attempt rolled back (prisma migrate resolve --rolled-back 20261010000000_coretax) and re-run prisma migrate deploy. Nothing was changed by this run.';
  END IF;

  -- 2. AUTO-FIX everything else that is not 16 digits, one audit row each.
  FOREACH t IN ARRAY ARRAY['company_settings', 'business_partners'] LOOP
    FOR r IN EXECUTE format($q$
      WITH s AS (
        SELECT id, npwp AS old_npwp,
               regexp_replace(npwp, '[.\-\s]', '', 'g') AS digits
        FROM %I WHERE npwp IS NOT NULL AND npwp !~ '^[0-9]{16}$'
      ), n AS (
        SELECT id, old_npwp, CASE
          WHEN digits ~ '^[0-9]{16}$' THEN digits
          WHEN digits ~ '^[0-9]{15}$' THEN '0' || digits
          ELSE NULL END AS new_npwp
        FROM s
      )
      UPDATE %I x SET npwp = n.new_npwp FROM n WHERE x.id = n.id
      RETURNING x.id, n.old_npwp, n.new_npwp$q$, t, t)
    LOOP
      -- audit_log is append-only for UPDATE / DELETE only; this INSERT
      -- commits or rolls back with the fix.
      INSERT INTO audit_log (id, method, path, body, status_code, duration_ms, entity_id)
      VALUES (gen_random_uuid()::text, 'MIGRATION', '20261010000000_coretax',
              jsonb_build_object('table', t, 'id', r.id,
                                 'old', r.old_npwp, 'new', r.new_npwp),
              200, 0, r.id);
    END LOOP;
  END LOOP;
END $$;

ALTER TABLE company_settings
  ADD CONSTRAINT company_settings_npwp_format CHECK (npwp IS NULL OR npwp ~ '^[0-9]{16}$'),
  ADD CONSTRAINT company_settings_coretax_codes_format CHECK (
    nitku_suffix ~ '^[0-9]{6}$'
    AND coretax_default_item_code ~ '^[0-9]{6}$'
    AND (coretax_default_unit_code IS NULL OR coretax_default_unit_code ~ '^UM\.[0-9]{4}$'));

ALTER TABLE business_partners
  ADD CONSTRAINT business_partners_npwp_format CHECK (npwp IS NULL OR npwp ~ '^[0-9]{16}$'),
  ADD CONSTRAINT business_partners_coretax_format CHECK (
    nitku_suffix ~ '^[0-9]{6}$'
    AND country ~ '^[A-Z]{3}$'
    AND (buyer_document_type <> 'NATIONAL_ID'
         OR buyer_document_number IS NULL
         OR buyer_document_number ~ '^[0-9]{16}$'));

ALTER TABLE tax_codes
  ADD CONSTRAINT tax_codes_coretax_vat_rate_range CHECK (
    coretax_vat_rate IS NULL OR (coretax_vat_rate > 0 AND coretax_vat_rate <= 100));

ALTER TABLE sales_invoice_lines
  ADD CONSTRAINT sales_invoice_lines_coretax_format CHECK (
    (coretax_item_code IS NULL OR coretax_item_code ~ '^[0-9]{6}$')
    AND (coretax_unit_code IS NULL OR coretax_unit_code ~ '^UM\.[0-9]{4}$'));

-- trx_code: the Coretax kode transaksi this API can export (07 / 08 need the
-- facility fields AddInfo / FacilityStamp, which it does not model).
-- APPROVED needs the NSFP and its date.
ALTER TABLE sales_invoices
  ADD CONSTRAINT sales_invoices_coretax_format CHECK (
    (trx_code IS NULL OR trx_code IN ('01', '02', '03', '04', '05', '06', '09', '10'))
    AND (tax_invoice_number IS NULL OR tax_invoice_number ~ '^[0-9]{17}$')
    AND (tax_invoice_status <> 'APPROVED'
         OR (tax_invoice_number IS NOT NULL AND tax_invoice_date IS NOT NULL)));

-- An NSFP identifies one faktur nationwide: unique among live invoices.
-- Expression index (btrim) so schema.prisma need not model it — same pattern
-- as purchase_bills_partner_vendor_invoice_norm_live_key; P2002 → 409.
CREATE UNIQUE INDEX sales_invoices_tax_invoice_number_live_key
  ON sales_invoices (btrim(tax_invoice_number))
  WHERE deleted_at IS NULL AND tax_invoice_number IS NOT NULL;

-- PMK 131/2024: the seeded PPN-OUT-11 (11% of DPP) is the 12% statutory rate
-- on DPP Nilai Lain 11/12 for non-luxury goods/services — the Coretax
-- presentation of the SAME amount (rate and postings unchanged).
UPDATE tax_codes SET dpp_nilai_lain = true, coretax_vat_rate = 12
WHERE code = 'PPN-OUT-11' AND kind = 'PPN_OUTPUT' AND rate = 0.11
  AND deleted_at IS NULL AND coretax_vat_rate IS NULL;
