import {
  AccountRole,
  AccountSubtype,
  AccountType,
  CashFlowCategory,
  NormalBalance,
} from '@prisma/client';

export interface SeedAccount {
  code: string;
  name: string;
  type: AccountType;
  subtype: AccountSubtype;
  normalBalance: NormalBalance;
  cashFlowCategory?: CashFlowCategory;
  role?: AccountRole;
  isPostable?: boolean;
  parentCode?: string;
}

/** SAK-aligned starting chart. Headers are non-postable; postable leaves carry balances. */
export const CHART_OF_ACCOUNTS: SeedAccount[] = [
  // 1 — Aset
  {
    code: '1-0000',
    name: 'Aset',
    type: 'ASSET',
    subtype: 'CURRENT_ASSET',
    normalBalance: 'DEBIT',
    isPostable: false,
  },
  {
    code: '1-1000',
    name: 'Kas',
    type: 'ASSET',
    subtype: 'CURRENT_ASSET',
    normalBalance: 'DEBIT',
    cashFlowCategory: 'OPERATING',
    role: 'CASH',
    parentCode: '1-0000',
  },
  {
    code: '1-1100',
    name: 'Bank',
    type: 'ASSET',
    subtype: 'CURRENT_ASSET',
    normalBalance: 'DEBIT',
    cashFlowCategory: 'OPERATING',
    role: 'CASH',
    parentCode: '1-0000',
  },
  {
    code: '1-1200',
    name: 'Piutang Usaha',
    type: 'ASSET',
    subtype: 'CURRENT_ASSET',
    normalBalance: 'DEBIT',
    cashFlowCategory: 'OPERATING',
    role: 'AR_CONTROL',
    parentCode: '1-0000',
  },
  {
    code: '1-1300',
    name: 'Persediaan',
    type: 'ASSET',
    subtype: 'CURRENT_ASSET',
    normalBalance: 'DEBIT',
    cashFlowCategory: 'OPERATING',
    parentCode: '1-0000',
  },
  {
    code: '1-1400',
    name: 'PPN Masukan',
    type: 'ASSET',
    subtype: 'TAX_RECEIVABLE',
    normalBalance: 'DEBIT',
    cashFlowCategory: 'OPERATING',
    parentCode: '1-0000',
  },
  {
    code: '1-1500',
    name: 'Uang Muka PPh',
    type: 'ASSET',
    subtype: 'TAX_RECEIVABLE',
    normalBalance: 'DEBIT',
    cashFlowCategory: 'OPERATING',
    parentCode: '1-0000',
  },
  {
    code: '1-1800',
    name: 'Perlengkapan',
    type: 'ASSET',
    subtype: 'CURRENT_ASSET',
    normalBalance: 'DEBIT',
    cashFlowCategory: 'OPERATING',
    parentCode: '1-0000',
  },
  {
    code: '1-2000',
    name: 'Aset Tetap',
    type: 'ASSET',
    subtype: 'FIXED_ASSET',
    normalBalance: 'DEBIT',
    cashFlowCategory: 'INVESTING',
    parentCode: '1-0000',
  },
  {
    code: '1-2900',
    name: 'Akumulasi Penyusutan',
    type: 'ASSET',
    subtype: 'ACCUMULATED_DEPRECIATION',
    normalBalance: 'CREDIT',
    cashFlowCategory: 'INVESTING',
    parentCode: '1-0000',
  },
  // 2 — Liabilitas
  {
    code: '2-0000',
    name: 'Liabilitas',
    type: 'LIABILITY',
    subtype: 'CURRENT_LIABILITY',
    normalBalance: 'CREDIT',
    isPostable: false,
  },
  {
    code: '2-1000',
    name: 'Utang Usaha',
    type: 'LIABILITY',
    subtype: 'CURRENT_LIABILITY',
    normalBalance: 'CREDIT',
    cashFlowCategory: 'OPERATING',
    role: 'AP_CONTROL',
    parentCode: '2-0000',
  },
  {
    code: '2-1100',
    name: 'PPN Keluaran',
    type: 'LIABILITY',
    subtype: 'TAX_PAYABLE',
    normalBalance: 'CREDIT',
    cashFlowCategory: 'OPERATING',
    parentCode: '2-0000',
  },
  {
    code: '2-1200',
    name: 'Utang PPh',
    type: 'LIABILITY',
    subtype: 'TAX_PAYABLE',
    normalBalance: 'CREDIT',
    cashFlowCategory: 'OPERATING',
    parentCode: '2-0000',
  },
  {
    code: '2-2000',
    name: 'Utang Bank',
    type: 'LIABILITY',
    subtype: 'NON_CURRENT_LIABILITY',
    normalBalance: 'CREDIT',
    cashFlowCategory: 'FINANCING',
    parentCode: '2-0000',
  },
  // 3 — Ekuitas
  {
    code: '3-0000',
    name: 'Ekuitas',
    type: 'EQUITY',
    subtype: 'EQUITY',
    normalBalance: 'CREDIT',
    isPostable: false,
  },
  {
    code: '3-1000',
    name: 'Modal',
    type: 'EQUITY',
    subtype: 'EQUITY',
    normalBalance: 'CREDIT',
    cashFlowCategory: 'FINANCING',
    parentCode: '3-0000',
  },
  {
    code: '3-2000',
    name: 'Laba Ditahan',
    type: 'EQUITY',
    subtype: 'EQUITY',
    normalBalance: 'CREDIT',
    cashFlowCategory: 'FINANCING',
    role: 'RETAINED_EARNINGS',
    parentCode: '3-0000',
  },
  {
    code: '3-9000',
    name: 'Saldo Awal',
    type: 'EQUITY',
    subtype: 'EQUITY',
    normalBalance: 'CREDIT',
    role: 'OPENING_BALANCE_EQUITY',
    parentCode: '3-0000',
  },
  // 4 — Pendapatan
  {
    code: '4-0000',
    name: 'Pendapatan',
    type: 'REVENUE',
    subtype: 'REVENUE',
    normalBalance: 'CREDIT',
    isPostable: false,
  },
  {
    code: '4-1000',
    name: 'Pendapatan Penjualan',
    type: 'REVENUE',
    subtype: 'REVENUE',
    normalBalance: 'CREDIT',
    cashFlowCategory: 'OPERATING',
    parentCode: '4-0000',
  },
  {
    code: '4-9000',
    name: 'Pendapatan Lain-lain',
    type: 'REVENUE',
    subtype: 'OTHER_INCOME',
    normalBalance: 'CREDIT',
    cashFlowCategory: 'OPERATING',
    parentCode: '4-0000',
  },
  // 5 — Beban
  {
    code: '5-0000',
    name: 'Beban',
    type: 'EXPENSE',
    subtype: 'OPERATING_EXPENSE',
    normalBalance: 'DEBIT',
    isPostable: false,
  },
  {
    code: '5-1000',
    name: 'Harga Pokok Penjualan',
    type: 'EXPENSE',
    subtype: 'COGS',
    normalBalance: 'DEBIT',
    cashFlowCategory: 'OPERATING',
    parentCode: '5-0000',
  },
  {
    code: '5-2000',
    name: 'Beban Gaji',
    type: 'EXPENSE',
    subtype: 'OPERATING_EXPENSE',
    normalBalance: 'DEBIT',
    cashFlowCategory: 'OPERATING',
    parentCode: '5-0000',
  },
  {
    code: '5-3000',
    name: 'Beban Sewa',
    type: 'EXPENSE',
    subtype: 'OPERATING_EXPENSE',
    normalBalance: 'DEBIT',
    cashFlowCategory: 'OPERATING',
    parentCode: '5-0000',
  },
  {
    code: '5-4000',
    name: 'Beban Operasional',
    type: 'EXPENSE',
    subtype: 'OPERATING_EXPENSE',
    normalBalance: 'DEBIT',
    cashFlowCategory: 'OPERATING',
    parentCode: '5-0000',
  },
  {
    code: '5-9000',
    name: 'Beban Pajak',
    type: 'EXPENSE',
    subtype: 'OTHER_EXPENSE',
    normalBalance: 'DEBIT',
    cashFlowCategory: 'OPERATING',
    role: 'TAX_EXPENSE',
    parentCode: '5-0000',
  },
];
